/**
 * KPI Newsletter - HTML 템플릿 조립 함수
 * 각 섹션의 HTML을 결합하여 완전한 KPI 뉴스레터 HTML 문서 생성
 */
import type { SupportedLanguage } from "../../config/style-guide";
import { KPI_COMMON_CSS } from "./common-css";

/**
 * KPI 섹션별 HTML 타입 정의
 */
export interface KpiSectionHTMLParts {
    header: string;
    summary: string;
    kpi: string;
    highlights: string;
    topics: string;
    ongoing: string;
    memberActivity: string;
    closing: string;
}

/**
 * 언어 코드로 HTML lang 속성값 취득
 */
function getLangCode(language: SupportedLanguage): string {
    switch (language) {
        case 'ja': return 'ja';
        case 'ko': return 'ko';
        default: return 'en';
    }
}

/**
 * 언어에 따른 푸터 메시지
 */
function getFooterMessages(language: SupportedLanguage): { generated: string; powered: string } {
    switch (language) {
        case 'ja':
            return {
                generated: 'このニュースレターはAIによって自動生成されました。',
                powered: '<p>Powered by <a href="https://nexone.ink">NexLetter</a></p>'
            };
        case 'ko':
            return {
                generated: '이 뉴스레터는 AI에 의해 자동 생성되었습니다.',
                powered: '<p>Powered by <a href="https://nexone.ink">NexLetter</a></p>'
            };
        default:
            return {
                generated: 'This newsletter was auto-generated by AI.',
                powered: '<p>Powered by <a href="https://nexone.ink">NexLetter</a></p>'
            };
    }
}

/**
 * KPI 뉴스레터용 완전한 HTML 문서를 조립
 * @param language 언어 코드
 * @param sections 각 섹션의 HTML
 * @returns 완전한 HTML 문서
 */
export function assembleKpiCompleteHTML(
    language: SupportedLanguage,
    sections: KpiSectionHTMLParts
): string {
    const langCode = getLangCode(language);
    const footer = getFooterMessages(language);

    const title = language === 'ja' ? 'KPIレポート'
        : language === 'ko' ? 'KPI 리포트'
        : 'KPI Report';

    const contentSections = [
        sections.kpi,
        sections.highlights,
        sections.topics,
        sections.ongoing,
        sections.memberActivity,
    ].filter(Boolean).join('\n');

    return `<!DOCTYPE html>
<html lang="${langCode}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${title}</title>
    <style>
${KPI_COMMON_CSS}
    </style>
</head>
<body>
    <div class="email-wrap">
        <div class="inner">
            ${sections.header}
            
            ${sections.summary}
            
            <div class="content">
                ${contentSections}
                
                ${sections.closing}
            </div>
            
            <div class="footer">
                <p>${footer.generated}</p>
                <p>${footer.powered}</p>
            </div>
        </div>
    </div>
</body>
</html>`;
}
