/**
 * HTMLテンプレート組み立て関数
 * 各セクションのHTMLを結合して完全なHTML文書を生成
 */
import type { SupportedLanguage } from "../../config/style-guide";
import { COMMON_CSS } from "./common-css";

/**
 * セクション別HTMLの型定義
 */
export interface SectionHTMLParts {
    header: string;
    summary: string;
    kpi: string;
    highlights: string;
    topics: string;
    ongoing: string;
    memberActivity: string;
    closing: string;
}

/**
 * 言語コードからHTML lang属性値を取得
 */
function getLangCode(language: SupportedLanguage): string {
    switch (language) {
        case 'ja': return 'ja';
        case 'ko': return 'ko';
        default: return 'en';
    }
}

/**
 * 言語に応じたフッターメッセージ
 */
function getFooterMessages(language: SupportedLanguage): { generated: string; powered: string } {
    switch (language) {
        case 'ja':
            return {
                generated: 'このニュースレターはAIによって自動生成されました。',
                powered: '<p>Powered by <a href="https://nexone.ink">IEUM</a></p>'
            };
        case 'ko':
            return {
                generated: '이 뉴스레터는 AI에 의해 자동 생성되었습니다.',
                powered: '<p>Powered by <a href="https://nexone.ink">IEUM</a></p>'
            };
        default:
            return {
                generated: 'This newsletter was auto-generated by AI.',
                powered: '<p>Powered by <a href="https://nexone.ink">IEUM</a></p>'
            };
    }
}

/**
 * 日付範囲からタイトルを生成
 */
function extractTitleFromHeader(headerHtml: string, language: SupportedLanguage): string {
    // headerHtmlからdate部分を抽出
    const dateMatch = headerHtml.match(/<h3 class="date">([^<]+)<\/h3>/);
    const dateRange = dateMatch ? dateMatch[1] : '';
    
    const titlePrefix = language === 'ja' ? '週次Newsletter' 
        : language === 'ko' ? '주간 뉴스레터'
        : 'Weekly Newsletter';
    
    return dateRange ? `${titlePrefix} — ${dateRange}` : titlePrefix;
}

/**
 * 完全なHTML文書を組み立てる
 * @param language 言語コード
 * @param sections 各セクションのHTML
 * @param isNoKpi KPIセクションを除外するかどうか
 * @returns 完全なHTML文書
 */
export function assembleCompleteHTML(
    language: SupportedLanguage,
    sections: SectionHTMLParts,
    isNoKpi: boolean = false
): string {
    const langCode = getLangCode(language);
    const footer = getFooterMessages(language);
    const title = extractTitleFromHeader(sections.header, language);
    
    // セクションを正しい順序で結合
    const contentSections = [
        sections.kpi && !isNoKpi ? sections.kpi : '',
        sections.highlights,
        sections.topics,
        sections.ongoing,
        sections.memberActivity,
    ].filter(Boolean).join('\n');

    return `<!DOCTYPE html>
<html lang="${langCode}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${title}</title>
    <style>
${COMMON_CSS}
    </style>
</head>
<body>
    <div class="email-wrap">
        <div class="inner">
            ${sections.header}
            
            ${sections.summary}
            
            <div class="content">
                ${contentSections}
                
                ${sections.closing}
            </div>
            
            <div class="footer">
                <p>${footer.generated}</p>
                <p>${footer.powered}</p>
            </div>
        </div>
    </div>
</body>
</html>`;
}

/**
 * KPI専用の完全なHTML文書を組み立てる
 * @param language 言語コード
 * @param kpiHtml KPIセクションのHTML
 * @returns 完全なHTML文書
 */
export function assembleKPIOnlyHTML(
    language: SupportedLanguage,
    kpiHtml: string,
    headerHtml?: string
): string {
    const langCode = getLangCode(language);
    const footer = getFooterMessages(language);
    const title = language === 'ja' ? 'KPIレポート' 
        : language === 'ko' ? 'KPI 리포트'
        : 'KPI Report';

    const header = headerHtml || `<div class="header"><h1>${title}</h1></div>`;

    return `<!DOCTYPE html>
<html lang="${langCode}">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${title}</title>
    <style>
${COMMON_CSS}
    </style>
</head>
<body>
    <div class="email-wrap">
        <div class="inner">
            ${header}
            
            <div class="content">
                ${kpiHtml}
            </div>
            
            <div class="footer">
                <p>${footer.generated}</p>
                <p>${footer.powered}</p>
            </div>
        </div>
    </div>
</body>
</html>`;
}
