export type PromptType = 
    'topic_clustering' 
    | 'activity_summary' 
    | 'highlights_summary'
    | 'ongoing_progress'
    | 'kpi_section'
    | 'highlights_section'
    | 'topics_section'
    | 'member_activity_section'
    | 'ongoing_section'
    | 'looking_ahead_section'
    | 'closing_section'
    | 'create_final_contents'
    | 'create_final_kpi'
    | 'convert_to_html'
    | 'convert_to_html_kpi'